# 此开源项目地址 https://github.com/lowlighter/metrics

name: GitHub Metrics

on:
  schedule:
    # Triggers on the 1st day of January, April, July, and October at midnight UTC
    - cron: "0 0 1 1,4,7,10 *"
  workflow_dispatch:
  
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # 基础信息（顺带了几个小插件）
      - name: base
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics/base.svg
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: Hongyang-Code
          template: classic
          config_timezone: Asia/Shanghai
          base: "header, activity, community, repositories"
          # 此插件为文档中的 🧮 Repositories traffic
          plugin_traffic: yes
          # 此插件为文档中的 👨‍💻 Lines of code changed
          plugin_lines: yes
          # 此插件为文档中的 🙋 Introduction
          plugin_introduction: yes
          # 此插件为文档中的 🎫 Gists
          plugin_gists: yes
          # 此插件为文档中的 💫 Star lists
          # plugin_starlists: yes
          # plugin_starlists_limit_repositories: 2
          # plugin_starlists_languages: yes
          # plugin_starlists_limit_languages: 8
          # plugin_starlists_only: Awesome
